// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFX97W6jl--jILh4EUJvFragnZokTN2ZI',
    appId: '1:882278911668:web:4fd3d67992b196a78991e1',
    messagingSenderId: '882278911668',
    projectId: 'waypoint-ae786',
    authDomain: 'waypoint-ae786.firebaseapp.com',
    storageBucket: 'waypoint-ae786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KEorCtm0LrKE0sF4LRp0YKj8_byHSw8',
    appId: '1:882278911668:android:73405103dbf314de8991e1',
    messagingSenderId: '882278911668',
    projectId: 'waypoint-ae786',
    storageBucket: 'waypoint-ae786.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFX97W6jl--jILh4EUJvFragnZokTN2ZI',
    appId: '1:882278911668:web:c25665b68ab848be8991e1',
    messagingSenderId: '882278911668',
    projectId: 'waypoint-ae786',
    authDomain: 'waypoint-ae786.firebaseapp.com',
    storageBucket: 'waypoint-ae786.firebasestorage.app',
  );
}
